apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azureshop.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azureshop.labels" . | nindent 4 }}
  # Annotations are used in Step 6.7 to bind Workload Identity
  # (azure.workload.identity/client-id: <managed-identity-client-id>)
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
