apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cart-service-secrets
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "d755c00c-d37e-47f8-997c-86202a2a77f4"
    keyvaultName: "kv-azureshop-6a6c-dev"
    tenantId: "4c135936-7e4d-4ea6-9816-7d696b51923d"
    objects: |
      array:
        - |
          objectName: redis-hostname
          objectType: secret
        - |
          objectName: redis-ssl-port
          objectType: secret
        - |
          objectName: redis-primary-access-key
          objectType: secret
        - |
          objectName: appinsights-cart-service-cs
          objectType: secret
  secretObjects:
    - secretName: cart-service-secrets
      type: Opaque
      data:
        - objectName: redis-hostname
          key: REDIS_HOST
        - objectName: redis-ssl-port
          key: REDIS_PORT
        - objectName: redis-primary-access-key
          key: REDIS_PASSWORD
        - objectName: appinsights-cart-service-cs
          key: APPINSIGHTS_CONNECTION_STRING
