apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: payment-service-secrets
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "d755c00c-d37e-47f8-997c-86202a2a77f4"
    keyvaultName: "kv-azureshop-6a6c-dev"
    tenantId: "4c135936-7e4d-4ea6-9816-7d696b51923d"
    objects: |
      array:
        - |
          objectName: sql-server-fqdn
          objectType: secret
        - |
          objectName: sql-admin-username
          objectType: secret
        - |
          objectName: sql-admin-password
          objectType: secret
        - |
          objectName: appinsights-payment-service-cs
          objectType: secret
  secretObjects:
    - secretName: payment-service-secrets
      type: Opaque
      data:
        - objectName: sql-server-fqdn
          key: SQL_SERVER
        - objectName: sql-admin-username
          key: SQL_USER
        - objectName: sql-admin-password
          key: SQL_PASSWORD
        - objectName: appinsights-payment-service-cs
          key: APPINSIGHTS_CONNECTION_STRING
