apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: product-service-secrets
  namespace: dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "d755c00c-d37e-47f8-997c-86202a2a77f4"
    keyvaultName: "kv-azureshop-6a6c-dev"
    tenantId: "4c135936-7e4d-4ea6-9816-7d696b51923d"
    objects: |
      array:
        - |
          objectName: cosmos-endpoint
          objectType: secret
        - |
          objectName: cosmos-primary-key
          objectType: secret
        - |
          objectName: appinsights-product-service-cs
          objectType: secret
  secretObjects:
    - secretName: product-service-secrets
      type: Opaque
      data:
        - objectName: cosmos-endpoint
          key: COSMOS_ENDPOINT
        - objectName: cosmos-primary-key
          key: COSMOS_KEY
        - objectName: appinsights-product-service-cs
          key: APPINSIGHTS_CONNECTION_STRING
